### ISSUE TITLE
Format the commit message

### ISSUE THREAD

**Issue by etorreborre** [chshersh/zbg#33]
One thing that I miss with `zbg` is a way to format the commit message like with the [`cmt`](https://github.com/smallhadroncollider/cmt#readme) Haskell tool. 

`zbg new` already goes in the direction of having some convention for branch names (with the `user.login` prefix), I think it would be good to go one step further with commit messages. This could be totally optional:

 - If a `.cmt` file is defined locally, use that file as a template for the commit message (see the [cmt demo](https://github.com/smallhadroncollider/cmt/blob/master/docs/cmt-0.7.gif))
 - If there is no `.cmt` file then let the user type a regular commit message.

**Comment by chshersh** [comment]
Hi @etorreborre 👋🏻 

Thanks for the idea! I'm not familiar with the `cmt` tool but it looks cool! 🚀 

I'm hesitant to reimplement an entire templating tool here and I personally don't use commit templates. If you have a `.cmt` commit template, can't you just use `cmt` instead of `zbg commit`?

On a separate note, I discovered that `git` itself supports commit templates natively via the `commit.template` option in `.gitconfig`:

* https://alex-wasik.medium.com/create-a-custom-git-commit-template-84468232a459

It might not be as flexible and powerful as `cmt` but IMO it's more portable and makes your workflow more universal.

Since `zbg commit` without arguments will call `git add .` followed by `git commit`, the latter will use `commit.template` and you can go from here.

Would it be enough?

**Comment by etorreborre** [comment]
My company is currently using (and enforcing) commit messages along [the conventialcommits format](https://www.conventionalcommits.org/en/v1.0.0/#summary). This is where `cmt` is useful. There's less chance of a making a mistake, and it saves some typing when prefixing the message with `refactor(rust)`.

Thanks for the pointer on git commit templates, I didn't know that such a thing existed. I will experiment with it. 
I totally understand why you would not want to re-implement a template system, no worries.
